spring:
  aplication:
    name: Fiskenatet
  jpa:
    hibernate:
      dialect: org.hibernate.dialect.MYSQLInnoDBDialect
      naming-strategy: org.hibernate.cfg.EJB3NamingStrategy
      ddl-auto: create-drop
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost/fiskenatet
    username: root
<<<<<<< HEAD
    password: Acmilan1
=======
    password: assassin723
>>>>>>> 662973277a2e0e0fdffa9a7b38a373f0eb05bf16
  jackson:
    serialization:
      fail-on-empty-beans: false

server:
  context-path: /api

logging:
  level:
    org.springframework.web: DEBUG
    org.hibernate: ERROR
    com.example.fiskenatet: INFO
