spring:
  aplication:
    name: Fiskenatet
  jpa:
    hibernate:
      dialect: org.hibernate.dialect.MYSQLInnoDBDialect
      naming-strategy: org.hibernate.cfg.EJB3NamingStrategy
      ddl-auto: update
<<<<<<< HEAD

=======
>>>>>>> 6b505a79275563650ebae9934f813a9b015e6ea7
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost/fiskenatet?useSSL=false
    username: root
<<<<<<< HEAD
    password: assassin723
=======
    password: mysql

>>>>>>> 6b505a79275563650ebae9934f813a9b015e6ea7

  jackson:
    serialization:
      fail-on-empty-beans: false

server:
  context-path: /api

logging:
  level:
    org.springframework.web: DEBUG
    org.hibernate: ERROR
    com.example.fiskenatet: INFO
